### ISSUE TITLE
BUG: Module `dns` doesn't exist

### ISSUE THREAD

**Issue by iop3** [VulcanWM/Drinks-Cabin#12]
Um when I tried  `pip install dns`, it returned 238459204893204 errors so...

And if this isn't maintained anymore I'll get lost, just say the word ;)

**Comment by VulcanWM** [comment]
It’s not `dns`, it’s `dnspython`

**Comment by iop3** [comment]
Oh.

> smh

**Comment by iop3** [comment]
`ModuleNotFoundError: No module named 'dns'` confused me
